name: Build and Push Client Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:19.03.12
        options: --privileged
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push client image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/ms-client:${{ github.sha }} ./MS-CLIENT
        docker tag ${{ secrets.DOCKER_USERNAME }}/ms-client:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/ms-client:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/ms-client:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USERNAME }}/ms-client:latest
