name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      id: run_tests  # Assign an ID to this step
      run: |
        pytest

    - name: Commit changes if there are any
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        if ! git diff-index --quiet HEAD; then
          git commit -m "Auto-commit: Fix tests or update"
          git push origin HEAD
        else
          echo "No changes to commit"
        fi

    - name: Push changes to main branch
      if: success()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Tests passed: pushing changes"
        git push origin main

    - name: Create and push a new branch with commit ID
      if: failure()  # This runs only if the tests fail
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        NEW_BRANCH="fix-tests-${{ github.sha }}"
        git checkout -b $NEW_BRANCH
        git add .
        git commit -m "Tests failed: moving changes to $NEW_BRANCH"
        git push origin $NEW_BRANCH
